---
version: '3.5'
services:
  quickvpn:
    image: giahuy2201/quickvpn:latest
    container_name: quickvpn
    restart: unless-stopped
    volumes:
      - ./config:/quickvpn/config
    ports:
      - 8000:80